### ISSUE TITLE
ImportError: No module named _bsddb

### ISSUE THREAD

**Issue by alexdotnet** [ddurdle/Python-GoogleDrive-VideoStream#134]
Hi,
with new version i'm unable to start default.py.
I'm using Mac Os... Same error in docker container..

Thanks...

Traceback (most recent call last):
  File "default.py", line 23, in <module>
    from resources.libgui import webgui
  File "/data/app/resources/libgui/webgui.py", line 34, in <module>
    import constants
  File "/data/app/constants.py", line 43, in <module>
    addon = xbmcaddon.xbmcaddon()
  File "/data/app/resources/libgui/xbmcaddon.py", line 43, in __init__
    self.dbm = settingsdbm.settingsdbm('./gdrive.db')
  File "/data/app/resources/libgui/settingsdbm.py", line 35, in __init__
    self.dbm = anydbm.open(dbmfile,'c')
  File "/usr/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb

**Comment by ddurdle** [comment]
https://stackoverflow.com/questions/16003224/installing-bsddb-package-python
