### ISSUE TITLE
Error generating streams

### ISSUE THREAD

**Issue by maximilianh75** [ddurdle/Python-GoogleDrive-VideoStream#26]
Host: localhost:9988
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: es-US,es-419;q=0.9,es;q=0.8

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 65001)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "F:\Aplicaciones\MEDIACENTERS\Python-GoogleDrive-VideoStream-master\Python-GoogleDrive-VideoStream-master\resources\libgui\webgui.py", line 1158, in do_GET
    mediaEngine.run(self,query, DBM=self.server.dbm, addon=self.server.addon)
  File "F:\Aplicaciones\MEDIACENTERS\Python-GoogleDrive-VideoStream-master\Python-GoogleDrive-VideoStream-master\resources\lib\engine.py", line 666, in run
    path = xbmcgui.Dialog().browse(0,addon.getLocalizedString(30026), 'files','',False,False,'')
AttributeError: 'Dialog' object has no attribute 'browse'
----------------------------------------

This error appear when try to save stream and access from url to be tested

**Comment by ddurdle** [comment]
have you been able to playback anything?

**Comment by maximilianh75** [comment]
Yes. but send me this error building the strm file

**Comment by maximilianh75** [comment]
Could you write a naming strm guide like you do in gdrive addon you wrote??

**Comment by HptmHavoc** [comment]
Probably you haven't set strm_path to a existing path. Try

`python2 setup.py -a strm_path existing/pat`h

or if the key/value already exist with -c to change it.

**Comment by maximilianh75** [comment]
Maybe I get a try

**Comment by HptmHavoc** [comment]
I forgot to mention that you can also set the path on the web settings page. 
Maybe if your current path do not work, try a simpler path f.e 

`F:\Aplicaciones\MEDIACENTERS\STRM`

But you have to create the folder STRM beforehand.

**Comment by maximilianh75** [comment]
Ok

**Comment by ddurdle** [comment]
in testing 0.1.10
