### ISSUE TITLE
strm creation fails or is inconsistent 

### ISSUE THREAD

**Issue by Dec64** [ddurdle/Python-GoogleDrive-VideoStream#52]
I have a large library in sections. E.g. Movies, Movies-4k, Movies-Kids. I want to keep them seperate. If I turn off the option for the script to create movies/tv/music/other and leave both boxes ticked to create original strms and google transcode strms. Then it will only create the orginal strms, no google transcode strms at all.

second issue seems to be that it does not find all my media, or seems to hang/stop for no reason and even if you re-try it will not find the other media.

Just tried to scan my movie folder and got the following error.

`----------------------------------------
Exception happened during processing of request from ('92.40.248.129', 44584)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/Python-GoogleDrive-VideoStream/resources/libgui/webgui.py", line 1076, in do_GET
    mediaEngine.run(self,query, DBM=self.server.dbm, addon=self.server.addon, host=host)
  File "/root/Python-GoogleDrive-VideoStream/resources/lib/engine.py", line 1066, in run
    (newcount,changeToken) = service.buildSTRM(self.plugin_handle, path,folderID, contentType=contentType, pDialog=pDialog, epath=encryptedPath, dpath=dencryptedPath, encfs=encfs, catalog=catalog, fetchChangeID=changeTracking, resolution=resolution, force=force, host=hostTemp,LOGGING=LOGGING, changeTracking=changeTracking, changeToken=changeToken,  skip0Res=skip0Res, original=original, transcode=transcode, append=append,removeExt=removeExt)
  File "/root/Python-GoogleDrive-VideoStream/resources/lib/cloudservice.py", line 180, in buildSTRM
    (newcount,nothing) = self.buildSTRM(plugin_handle,path + '/'+str(item.folder.title), item.folder.id, pDialog=pDialog, spreadsheetFile=spreadsheetFile, catalog=catalog, musicPath=musicPath, moviePath=moviePath,tvPath=tvPath,videoPath=videoPath, resolution=resolution, LOGGING=LOGGING, host=host, skip0Res=skip0Res, original=original, transcode=transcode, append=append, removeExt=removeExt)
  File "/root/Python-GoogleDrive-VideoStream/resources/lib/cloudservice.py", line 170, in buildSTRM
    mediaItems = self.getMediaList(folderID,contentType=contentType)
  File "/root/Python-GoogleDrive-VideoStream/resources/lib/gdrive_api2.py", line 449, in getMediaList
    if e.code == 403 or e.code == 401:
AttributeError: 'URLError' object has no attribute 'code'
----------------------------------------`

**Comment by Dec64** [comment]
It seems to timeout after about 2 to 3mins. If i watch the folder it's creating strms in `Apr 27 10:45` is the first and then `Apr 27 10:47` is the last time files are created. No error, just stops, the web page shows a timeout. Or nothing if triggered by a schedule.

**Comment by ddurdle** [comment]
Timeout only happens when you have catalog = false?

**Comment by Dec64** [comment]
```This page isn’t working
212.47.252.232 didn’t send any data.
ERR_EMPTY_RESPONSE```

**Comment by ddurdle** [comment]
I did some testing today.  I had a manual STRM creation (catalog method) performed on a 75TB drive.  It started at 12:13pm and ended at 12:55pm (so approx 42mins).  It returned response 200 and reported creating 15929 STRMs.

**Comment by ddurdle** [comment]
The google transcode files not being created is related to this (and since fixed):
https://github.com/ddurdle/Python-GoogleDrive-VideoStream/issues/53

I'm fraying away from suggesting separate files to be created for original and google transcode versions.  I am testing a custom ffmpeg wrapper script that can be deployed that will allow you to toggle between original and google transcode versions by using the emby quality selector (that shows up during playback).  This would be ideal for now since there are two open issues with Emby around their multiple STRM quality selector dialog (first being,  the media is not probed so codec info is absent and resume is disabled and second being, it currently is only supported for movies).

**Comment by Dec64** [comment]
Nice, sorry on the delayed response, just come back to this after being very busy. Updates have fixed this issue nice. Any movement on that ffmpeg wrapper script?

**Comment by ddurdle** [comment]
script is here: https://github.com/ddurdle/GoogleDrive-VideoStream_extra

There are a bunch of various helper scripts.  The one for overriding the transcode is stored in the transcoding directory.

You just need to update the port (if you change it from 9988), then this script will intercept the calls to the plugin.

You swap it in place by renaming the originals to .oem which are called by this wrapper script.  You don't need to override the ffprobe, I'm overriding it to filter out embedded subtitles since they don't work well.

cd  /opt/emby-server/bin
sudo mv ffmpeg ffmpeg.oem
sudo mv ffprobe ffprobe.oem
sudo ln -sf /u01/GoogleDrive-VideoStream_extra/transcoders/emby_ffmpeg.pl ffmpeg
sudo ln -sf /u01/GoogleDrive-VideoStream_extra/transcoders/emby_ffprobe.pl ffprobe

**Comment by Dec64** [comment]
Sounds perfect.

So just to clarify, what options should be enabled when creating the single strm per movie? Just "create original quality STRM files" right?
